# Generated by Django 4.1.7 on 2023-03-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Buyers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
