# Generated by Django 4.1.7 on 2023-03-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Buyers", "0002_alter_products_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="last_update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
