# Generated by Django 4.1.7 on 2023-03-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Buyers", "0003_products_last_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
