# Generated by Django 4.1.7 on 2023-04-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Buyers", "0004_alter_order_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="description",
            field=models.CharField(blank=True, default="", max_length=2500, null=True),
        ),
    ]
