# Generated by Django 4.1.7 on 2023-04-04 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Buyers", "0004_alter_order_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="likes",
            field=models.ManyToManyField(
                related_name="blogpost_like", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
