# Generated by Django 4.1.7 on 2023-04-05 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Buyers", "0005_products_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="likes",
            field=models.ManyToManyField(
                related_name="each_product_like", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
