# Generated by Django 4.1.7 on 2023-04-26 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Buyers", "0005_alter_products_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category_v",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Products_v",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("description", models.CharField(max_length=2500)),
                ("image", models.ImageField(upload_to="uploads/products/")),
                ("status", models.BooleanField(default=True)),
                ("ownerid", models.PositiveSmallIntegerField(default=1)),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Buyers.category_v",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Buyers.products_v"
            ),
        ),
    ]
