# Generated by Django 4.1.7 on 2023-04-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Buyers", "0007_alter_products_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="each_product_like", to="Buyers.customer"
            ),
        ),
    ]
