# Generated by Django 4.1.7 on 2023-04-26 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Buyers", "0007_remove_products_v_category_alter_order_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Buyers.products"
            ),
        ),
    ]
