# Generated by Django 4.1.7 on 2023-04-27 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Vendors", "0009_remove_products_v_owner_products_v_ownerid"),
        ("Buyers", "0008_alter_order_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Vendors.products_v"
            ),
        ),
    ]
