# Generated by Django 4.1.7 on 2023-04-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Buyers", "0009_alter_products_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="like_product", to="Buyers.customer"
            ),
        ),
    ]
