# Generated by Django 4.1.7 on 2023-04-28 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Buyers", "0010_customer_customer_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="customer_picture",
            new_name="profile_picture",
        ),
    ]
