# Generated by Django 4.1.7 on 2023-04-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Buyers", "0011_alter_products_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="description",
            field=models.CharField(blank=True, default="", max_length=5000, null=True),
        ),
    ]
