# Generated by Django 4.1.7 on 2023-04-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Buyers", "0011_rename_customer_picture_customer_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="profile_picture",
            field=models.ImageField(default=1, upload_to="uploads/profile/"),
            preserve_default=False,
        ),
    ]
