# Generated by Django 4.1.7 on 2023-04-08 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Buyers", "0012_alter_products_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="likes",
            field=models.ManyToManyField(
                related_name="like_product", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
