# Generated by Django 4.1.7 on 2023-05-05 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Buyers", "0012_alter_customer_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(model_name="products", name="category",),
        migrations.DeleteModel(name="Category",),
        migrations.DeleteModel(name="Products",),
    ]
