# Generated by Django 4.1.7 on 2023-04-08 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Buyers", "0014_alter_products_likes_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
