# Generated by Django 4.1.7 on 2023-04-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Vendors", "0002_category_products"),
    ]

    operations = [
        migrations.RenameModel(old_name="Category", new_name="Category_v",),
        migrations.RenameModel(old_name="Products", new_name="Products_v",),
    ]
