# Generated by Django 4.1.7 on 2023-04-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Vendors", "0004_remove_products_v_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products_v",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
