# Generated by Django 4.1.7 on 2023-04-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Vendors", "0005_products_v_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category_v",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
