# Generated by Django 4.1.7 on 2023-04-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Vendors", "0006_alter_category_v_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products_v",
            name="description",
            field=models.CharField(default=1, max_length=2500),
            preserve_default=False,
        ),
    ]
