# Generated by Django 4.1.7 on 2023-04-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Vendors", "0007_alter_products_v_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="products_v",
            name="owner",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
