# Generated by Django 4.1.7 on 2023-04-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Vendors", "0008_products_v_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products_v",
            name="owner",
        ),
        migrations.AddField(
            model_name="products_v",
            name="ownerid",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
