# Generated by Django 4.1.7 on 2023-04-29 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Vendors", "0009_remove_products_v_owner_products_v_ownerid"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendors",
            name="member_since",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
