# Generated by Django 4.1.7 on 2023-04-28 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Vendors", "0009_remove_products_v_owner_products_v_ownerid"),
    ]

    operations = [
        migrations.AddField(
            model_name="products_v",
            name="vendor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Vendors.vendors",
            ),
        ),
    ]
