# Generated by Django 4.1.7 on 2023-05-01 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Vendors", "0010_vendors_member_since"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendors",
            name="open_hour",
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name="vendors",
            name="to_hour",
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
    ]
