# Generated by Django 4.1.7 on 2023-05-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Vendors", "0011_remove_products_v_vendor"),
        ("Vendors", "0011_vendors_open_hour_vendors_to_hour"),
    ]

    operations = []
