# Generated by Django 4.1.7 on 2023-05-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Vendors", "0010_vendors_member_since"),
        ("Vendors", "0011_remove_products_v_vendor"),
    ]

    operations = []
