# Generated by Django 4.1.7 on 2023-05-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Vendors", "0011_vendors_open_hour_vendors_to_hour"),
        ("Vendors", "0012_merge_20230503_0006"),
    ]

    operations = []
